import { CSSProperties } from 'react';

type StylesObject = {
  [key: string]: CSSProperties & {
    '&:hover'?: CSSProperties;
    '&:focus'?: CSSProperties;
  };
};

const formstyles: StylesObject = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#ffffff',
    padding: '2rem 1rem',
    display: 'flex',
    justifyContent: 'center',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
  },
  formContainer: {
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    backgroundColor: 'white',
    borderRadius: '1rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    overflow: 'hidden',
    border: '1px solid #e2e8f0',
  },
  header: {
    padding: '1.75rem 2.5rem',
    color: '#2D2D8F',
    borderBottom: '1px solid #1e3a8a',
  },
  headerTitle: {
    fontSize: '17px',
    fontWeight: '700',
    letterSpacing: '0.025em',
    margin: 0,
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
  },
  formBody: {
    padding: '2.5rem',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
    gap: '2rem',
  },
  formGroup: {
    marginBottom: '1.5rem',
    position: 'relative',
  },
  label: {
    display: 'block',
    fontSize: '15px',
    fontWeight: '400',
    color: '#2D2D8F',
    marginBottom: '0.5rem',
  },
  input: {
    width: '100%',
    padding: '0.45rem 1rem',
    border: '1px solid #cbd5e1',
    borderRadius: '0.5rem',
    fontSize: '0.9rem',
    transition: 'all 0.2s ease',
    backgroundColor: 'white',
    color: '#2D2D8F',
    boxSizing: 'border-box',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    outline: 'none',
    '&:focus': {
      borderColor: '#2D2D8F',
      boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.25)',
    },
    '&:hover': {
      borderColor: '#94a3b8',
    },
  },
  inputError: {
    borderColor: '#ef4444',
    backgroundColor: 'white',
    boxShadow: '0 0 0 1px #ef4444',
    '&:focus': {
      boxShadow: '0 0 0 3px rgba(239, 68, 68, 0.25)',
    },
  },
  select: {
    width: '100%',
    padding: '0.45rem 1rem',
    border: '1px solid #cbd5e1',
    borderRadius: '0.5rem',
    fontSize: '0.9rem',
    backgroundColor: 'white',
    color: '#2D2D8F',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    appearance: 'none',
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke='%2364748b'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M19 9l-7 7-7-7'%3E%3C/path%3E%3C/svg%3E")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 0.75rem center',
    backgroundSize: '1.25rem',
    paddingRight: '2.5rem',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    outline: 'none',
    '&:focus': {
      borderColor: '#2d2d8f',
      boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.25)',
    },
    '&:hover': {
      borderColor: '#94a3b8',
    },
  },
  scheduleBox: {
    border: '1px solid #e2e8f0',
    borderRadius: '0.5rem',
    padding: '1.5rem',
    backgroundColor: '#f8fafc',
    boxShadow: 'inset 0 1px 2px rgba(0, 0, 0, 0.05)',
  },
  monthlyOptions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: '#f8fafc',
    borderRadius: '0.5rem',
    border: '1px solid #e2e8f0',
  },
  radioGroup: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '1rem',
    gap: '1rem',
  },
  radioLabel: {
    width: '100px',
    fontSize: '0.9rem',
    color: '#475569',
    fontWeight: '500',
  },
  radioButtons: {
    display: 'flex',
    border: '1px solid #2D2D8F',
    borderRadius: '0.5rem',
    overflow: 'hidden',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
  },
  radioOption: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.9rem',
    color: '#475569',
    cursor: 'pointer',
    userSelect: 'none',
  },
  radioActive: {
    backgroundColor: '#2D2D8F',
    color: 'white',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
  },
  radioInactive: {
    backgroundColor: '#f8fafc',
    color: '#64748b',
    '&:hover': {
      backgroundColor: '#f1f5f9',
    },
  },
  buttonGroup: {
    marginTop: '3rem',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
  },
  button: {
    padding: '0.75rem 1.75rem',
    borderRadius: '0.5rem',
    fontWeight: '500',
    fontSize: '0.9rem',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    border: 'none',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    outline: 'none',
  },
  cancelButton: {
    backgroundColor: '#f1f5f9',
    color: '#475569',
    '&:hover': {
      backgroundColor: '#e2e8f0',
      color: '#334155',
    },
    '&:focus': {
      boxShadow: '0 0 0 3px rgba(148, 163, 184, 0.4)',
    },
  },
  submitButton: {
    backgroundColor: '#2d2d8f',
    color: 'white',
    '&:hover': {
      backgroundColor: '#2563eb',
    },
    '&:focus': {
      boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.4)',
    },
  },
  disabledButton: {
    opacity: '0.6',
    cursor: 'not-allowed',
    pointerEvents: 'none',
  },
  successAlert: {
    margin: '1.5rem 2.5rem 0',
    padding: '1rem 1.25rem',
    backgroundColor: '#f0fdf4',
    color: '#166534',
    borderRadius: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    border: '1px solid #bbf7d0',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
    animation: 'fadeIn 0.3s ease-in-out',
  },
  errorAlert: {
    margin: '1.5rem 2.5rem 0',
    padding: '1rem 1.25rem',
    backgroundColor: '#fef2f2',
    color: '#991b1b',
    borderRadius: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    border: '1px solid #fecaca',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
    animation: 'fadeIn 0.3s ease-in-out',
  },
  alertIcon: {
    marginRight: '0.75rem',
    flexShrink: 0,
  },
  errorText: {
    color: '#ef4444',
    fontSize: '0.75rem',
    marginTop: '0.375rem',
    fontWeight: '500',
    animation: 'fadeIn 0.2s ease-in-out',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
    backdropFilter: 'blur(4px)',
    animation: 'fadeIn 0.2s ease-in-out',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: '2.5rem',
    borderRadius: '0.75rem',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    width: '480px',
    maxWidth: '90vw',
    maxHeight: '85vh',
    overflow: 'auto',
    animation: 'slideUp 0.3s ease-in-out',
    border: '1px solid #e2e8f0',
  },
  modalTitle: {
    fontSize: '1.375rem',
    fontWeight: '600',
    color: '#1e293b',
    marginBottom: '1.5rem',
    paddingBottom: '0.75rem',
    borderBottom: '1px solid #e2e8f0',
  },
  modalButtons: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
    marginTop: '2.5rem',
  },
  recurrenceInfo: {
    marginTop: '1rem',
    padding: '1rem',
    backgroundColor: '#eff6ff',
    borderRadius: '0.5rem',
    fontSize: '0.9rem',
    color: '#1e40af',
    border: '1px solid #bfdbfe',
    boxShadow: 'inset 0 1px 2px rgba(0, 0, 0, 0.05)',
    lineHeight: '1.5',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '0.9rem',
    color: '#475569',
    cursor: 'pointer',
    userSelect: 'none',
    '&:hover': {
      color: '#334155',
    },
  },
  checkbox: {
    marginRight: '0.625rem',
    width: '1.125rem',
    height: '1.125rem',
    borderRadius: '0.25rem',
    border: '1px solid #cbd5e1',
    cursor: 'pointer',
    accentColor: '#2d2d8f',
    '&:hover': {
      borderColor: '#94a3b8',
    },
    '&:focus': {
      outline: 'none',
      boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.25)',
    },
  },
  dateTimePicker: {
    width: '100%',
    padding: '0.45rem 1rem',
    border: '1px solid #cbd5e1',
    borderRadius: '0.5rem',
    fontSize: '0.9rem',
    backgroundColor: 'white',
    color: '#1e293b',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
    outline: 'none',
    '&:focus': {
      borderColor: '#2d2d8f',
      boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.25)',
    },
  },
  dateTimeLabel: {
    fontSize: '0.8rem',
    color: '#64748b',
    marginBottom: '0.375rem',
    fontWeight: '500',
  },
  dateTimeInput: {
    marginBottom: '1rem',
  },
  radio: {
    accentColor: '#2d2d8f',
    width: '1.125rem',
    height: '1.125rem',
    marginRight: '0.5rem',
    cursor: 'pointer',
  },
} as const;

export default formstyles;