import { createSlice } from "@reduxjs/toolkit";
import { RootState } from "../../../app/store";
// import { fetchCount } from './counterAPI';

export interface FinopsDataInterface {
  //   value: number;
  azureDailyUsage: [];
  awsDailyUsage: [];
  gcpDailyUsage: [];
  finopsazureDailyUsage: [];
  finopsawsDailyUsage: [];
  finopsgcpDailyUsage: [];
  azureForecast: [];
  awsForecast: [];
  gcpForecast: [];
  finopsazureForecast: [];
  finopsawsForecast: [];
  finopsgcpForecast: [];
  finopsToken: string;
  toValue: "",
  fromValue: "",
  finOpsBudget: {},
  finOpsTotalCost : {}
}

const initialState: FinopsDataInterface = {
  //   value: 0,
  azureDailyUsage: [],
  awsDailyUsage: [],
  gcpDailyUsage: [],
  finopsazureDailyUsage: [],
  finopsawsDailyUsage: [],
  finopsgcpDailyUsage: [],
  azureForecast: [],
  awsForecast: [],
  gcpForecast: [],
  finopsazureForecast: [],
  finopsawsForecast: [],
  finopsgcpForecast: [],
  finopsToken: "",
  toValue: "",
  fromValue: "",
  finOpsBudget: {},
  finOpsTotalCost: {}
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
// export const incrementAsync = createAsyncThunk(
//   'counter/fetchCount',
//   async (amount: number) => {
//     const response = await fetchCount(amount);
//     // The value we return becomes the `fulfilled` action payload
//     return response.data;
//   }
// );

export const FinopsDataSlice = createSlice({
  name: "FinopsDataSlice",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setAzureDailyUsage: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.azureDailyUsage = action.payload;
    },
    setAwsDailyUsage: (state, action) => {
      state.awsDailyUsage = action.payload;
    },
    setGcpDailyUsage: (state, action) => {
      state.gcpDailyUsage = action.payload;
    },
    setFinopsAzureDailyUsage: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.finopsazureDailyUsage = action.payload;
    },
    setFinopsAwsDailyUsage: (state, action) => {
      state.finopsawsDailyUsage = action.payload;
    },
    setFinopsGcpDailyUsage: (state, action) => {
      state.finopsgcpDailyUsage = action.payload;
    },
    setFinopsToken: (state, action) => {
      state.finopsToken = action.payload;
    },
    setAwsForecast: (state, action) => {
      state.awsForecast = action.payload;
    },
    setAzureForecast: (state, action) => {
      state.azureForecast = action.payload;
    },
    setGcpForecast: (state, action) => {
      state.gcpForecast = action.payload;
    },
    setFinopsAwsForecast: (state, action) => {
      state.finopsawsForecast = action.payload;
    },
    setFinopsAzureForecast: (state, action) => {
      state.finopsazureForecast = action.payload;
    },
    setFinopsGcpForecast: (state, action) => {
      state.finopsgcpForecast = action.payload;
    },
    setToValue: (state, action) => {
      state.toValue = action.payload;
    },
    setFromValue: (state, action) => {
      state.fromValue = action.payload;
    },
    SetFinOpsBudget: (state, action) => {
      state.finOpsBudget = action.payload;
    },
    resetFinopsData: (state) => {
      state = initialState;
    },
    setFinOpsTotalCost: (state, action) => {
      state.finOpsTotalCost = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const {
  setAzureDailyUsage,
  setAwsDailyUsage,
  setGcpDailyUsage,
  setFinopsToken,
  setFinopsAwsDailyUsage,
  setFinopsAzureDailyUsage,
  setGcpForecast,
  setAzureForecast,
  setAwsForecast,
  setFinopsGcpForecast,
  setFinopsAzureForecast,
  setFinopsAwsForecast,
  setFinopsGcpDailyUsage,
  resetFinopsData,
  setFromValue,
  setToValue,
  setFinOpsTotalCost,
  SetFinOpsBudget
} = FinopsDataSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectFinopsData = (state: RootState) => state.finopsData;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectCount(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount));
//     }
//   };

export default FinopsDataSlice.reducer;
